name: Run Tests by Application

on:
  workflow_dispatch:
    inputs:
      applicationName:
        description: 'Application Name (e.g., user api suite demo)'
        required: true
        type: string
      testType:
        description: 'Test Type Filter'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - API
          - UI
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'qa'
        type: choice
        options:
          - dev
          - qa
          - prod
      parallel:
        description: 'Run tests in parallel'
        required: false
        default: true
        type: boolean

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.8.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          ENV: ${{ github.event.inputs.environment }}
        run: |
          echo "Running tests for application: ${{ github.event.inputs.applicationName }}"
          echo "Test type: ${{ github.event.inputs.testType }}"
          echo "Environment: $ENV"

          # Build CLI args dynamically
          ARGS="--applicationName=${{ github.event.inputs.applicationName }}"

          if [ "${{ github.event.inputs.testType }}" != "all" ]; then
            ARGS="$ARGS --testType=${{ github.event.inputs.testType }}"
          fi

          echo "Executing: npx ts-node src/runner.ts $ARGS"
          npx ts-node src/runner.ts $ARGS

      - name: Generate HTML reports
        if: always()
        run: npm run report:html

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ github.event.inputs.applicationName }}-${{ github.event.inputs.environment }}
          path: reports/
          retention-days: 30

      - name: Upload HTML reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: html-reports-${{ github.event.inputs.applicationName }}-${{ github.event.inputs.environment }}
          path: '**/*.html'
          retention-days: 30
